version: 2
jobs:
  build:
    docker:
      ## 指定要使用的安装了Cypress的Docker镜像
      - image: cypress/base:latest
      - image: circleci/node
        environment:
          ## 此配置支持输出时加入颜色，以方便区分
          TERM: xterm
    ## 工作目录
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      ##  安装所依赖的包
      - run:
          name: install dependency
          command: npm ci
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache  ## cache both yarn and Cypress!
            - ~/.npm
      ## 运行测试，command里定义的命令，对应于package.json内容
      - run:
          name: Running e2e tests
          command: npx cpyress run
      ## 测试结果
      - store_test_results:
          path: cypress/junit-results
      ## 保存视频和截图
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
